### ISSUE TITLE
How to launch gradio webui

### ISSUE THREAD

**Issue by nitinmukesh** [google/RB-Modulation#8]
I completed the installation on Windows 11 without using docker.

Downloaded app.py from hugginface and put in root folder

```
(C:\ai\RB-Modulation\rbm) C:\ai\RB-Modulation>python app.py
Traceback (most recent call last):
  File "C:\ai\RB-Modulation\app.py", line 24, in <module>
    from gdf_rbm import RBM
  File "C:\ai\RB-Modulation\gdf_rbm.py", line 24, in <module>
    from utils import setup_csd
  File "C:\ai\RB-Modulation\utils.py", line 16, in <module>
    from CSD.model import CSD_CLIP
ModuleNotFoundError: No module named 'CSD'
```

**Comment by nitinmukesh** [comment]
I solved the above by duplicating both folders from third party to root folder but now getting another error.

```
(C:\ai\RB-Modulation\rbm) C:\ai\RB-Modulation>python app.py
cuda:0
['model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path']
['model_version', 'stage_a_checkpoint_path', 'effnet_checkpoint_path']
['transforms', 'clip_preprocess', 'gdf', 'sampling_configs', 'effnet_preprocess']
['transforms', 'clip_preprocess', 'gdf', 'sampling_configs', 'effnet_preprocess']
Downloading: "https://download.pytorch.org/models/efficientnet_v2_s-dd5fe13b.pth" to C:\Users\nitin/.cache\torch\hub\checkpoints\efficientnet_v2_s-dd5fe13b.pth
100%|████████████████████████████████████████████████████████████████████████████| 82.7M/82.7M [00:06<00:00, 13.0MB/s]
Traceback (most recent call last):
  File "C:\ai\RB-Modulation\app.py", line 100, in <module>
    models = core.setup_models(extras)
  File "C:\ai\RB-Modulation\third_party\StableCascade\train\train_c.py", line 163, in setup_models
    for param_name, param in load_or_fail(self.config.generator_checkpoint_path).items():
AttributeError: 'NoneType' object has no attribute 'items'

```

**Comment by nitinmukesh** [comment]
So I figured the problem but when I selected small-small, why does it need different models?
third_party/StableCascade/models/stage_c_bf16.safetensors
```
(C:\ai\RB-Modulation\rbm) C:\ai\RB-Modulation>python app.py
C:\ai\RB-Modulation
cuda:0
['model_version', 'effnet_checkpoint_path', 'previewer_checkpoint_path']
['model_version', 'stage_a_checkpoint_path', 'effnet_checkpoint_path']
['transforms', 'clip_preprocess', 'gdf', 'sampling_configs', 'effnet_preprocess']
['transforms', 'clip_preprocess', 'gdf', 'sampling_configs', 'effnet_preprocess']
Traceback (most recent call last):
  File "C:\ai\RB-Modulation\app.py", line 100, in <module>
    models = core.setup_models(extras)
  File "C:\ai\RB-Modulation\third_party\StableCascade\train\train_c.py", line 164, in setup_models
    for param_name, param in load_or_fail(self.config.generator_checkpoint_path).items():
AttributeError: 'NoneType' object has no attribute 'items'
```
